version: "3.9"

services:
    front-end:
        build: ./public
        restart: unless-stopped
        ports:
            -   8080:80

    back-end:
        build: ./server
        restart: unless-stopped
        ports:
            -   8081:8081

