version: "3.9"

services:
    front-end:
        container_name: front-end
        hostname: front-end
        build: ./public
        restart: unless-stopped
        volumes:
            - ${PWD}/public/nginx.conf:/etc/nginx/nginx.conf
        ports:
            -   8080:80

    back-end:
        container_name: back-end
        hostname: back-end
        build: ./server
        restart: unless-stopped
